import type { SceneObject } from "../store/scene";

// Inspirado en Spline: objetos grandes, repartidos por el viewport,
// algunos cortados en bordes, fondo negro, paleta vibrante sobre oscuro.
export const epicHeroTemplate: Omit<SceneObject, "id">[] = [
  // === CENTRO-IZQUIERDA: roundedBox grande con glass, protagonista ===
  {
    name: "Glass Slab L",
    geometry: "roundedBox",
    material: "transmission",
    animation: "float",
    position: [-3, -0.5, 0],
    rotation: [0.2, -0.3, -0.15],
    scale: [3.5, 3.5, 0.4],
    color: "#6366f1",
    metalness: 0,
    roughness: 0,
    transmission: 0.92,
    thickness: 1.2,
  },
  // === DERECHA: roundedBox grande con glass verde ===
  {
    name: "Glass Slab R",
    geometry: "roundedBox",
    material: "transmission",
    animation: "float",
    position: [4.5, -1, -1],
    rotation: [-0.15, 0.4, 0.1],
    scale: [3.2, 3.2, 0.35],
    color: "#10b981",
    metalness: 0,
    roughness: 0,
    transmission: 0.9,
    thickness: 1,
  },
  // === ARRIBA DERECHA: roundedBox mediano azul, cortado en borde ===
  {
    name: "Float Tile TR",
    geometry: "roundedBox",
    material: "standard",
    animation: "float",
    position: [5, 3, -2],
    rotation: [0.1, -0.2, 0.05],
    scale: [2, 2, 0.3],
    color: "#4f46e5",
    metalness: 0.7,
    roughness: 0.25,
  },
  // === IZQUIERDA ABAJO: roundedBox rosa/pink ===
  {
    name: "Pink Tile BL",
    geometry: "roundedBox",
    material: "standard",
    animation: "float",
    position: [-5.5, -2.5, -1.5],
    rotation: [-0.1, 0.3, 0.2],
    scale: [1.8, 1.8, 0.3],
    color: "#ec4899",
    metalness: 0.5,
    roughness: 0.3,
  },
  // === ARRIBA IZQUIERDA: esfera glass pequeña ===
  {
    name: "Bubble TL",
    geometry: "sphere",
    material: "transmission",
    animation: "float",
    position: [-2, 3.5, -1],
    rotation: [0, 0, 0],
    scale: [0.6, 0.6, 0.6],
    color: "#c084fc",
    metalness: 0,
    roughness: 0,
    transmission: 0.95,
    thickness: 0.3,
  },
  // === CENTRO DERECHA: dodecaedro verde pequeño flotando ===
  {
    name: "Gem Green",
    geometry: "dodecahedron",
    material: "standard",
    animation: "float",
    position: [1.5, 0.5, 1],
    rotation: [0.3, 0.5, 0],
    scale: [0.55, 0.55, 0.55],
    color: "#34d399",
    metalness: 0.6,
    roughness: 0.2,
  },
  // === IZQUIERDA MEDIA: esfera amarilla pequeña, accent ===
  {
    name: "Accent Yellow",
    geometry: "sphere",
    material: "standard",
    animation: "float",
    position: [-4.5, 0.5, 0.5],
    rotation: [0, 0, 0],
    scale: [0.5, 0.5, 0.5],
    color: "#facc15",
    metalness: 0.4,
    roughness: 0.3,
  },
  // === DERECHA BORDE: roundedBox violeta grande, cortado ===
  {
    name: "Edge Slab R",
    geometry: "roundedBox",
    material: "standard",
    animation: "float",
    position: [7, 0.5, -3],
    rotation: [0.05, -0.5, -0.1],
    scale: [2.5, 2.5, 0.3],
    color: "#7c3aed",
    metalness: 0.65,
    roughness: 0.2,
  },
  // === ARRIBA CENTRO: esfera glass oscura, sutil ===
  {
    name: "Dark Sphere",
    geometry: "sphere",
    material: "standard",
    animation: "none",
    position: [0.5, 4, -3],
    rotation: [0, 0, 0],
    scale: [0.45, 0.45, 0.45],
    color: "#374151",
    metalness: 0.8,
    roughness: 0.1,
  },
  // === DERECHA MEDIA: esfera pink accent ===
  {
    name: "Accent Pink",
    geometry: "sphere",
    material: "standard",
    animation: "float",
    position: [5.5, 1.5, -0.5],
    rotation: [0, 0, 0],
    scale: [0.55, 0.55, 0.55],
    color: "#f472b6",
    metalness: 0.5,
    roughness: 0.3,
  },
  // === CENTRO ABAJO: torus sutil, como detalle ===
  {
    name: "Subtle Ring",
    geometry: "torus",
    material: "standard",
    animation: "rotate",
    position: [0, -1.5, 1],
    rotation: [Math.PI / 2, 0, 0],
    scale: [1.5, 1.5, 1.5],
    color: "#6366f1",
    metalness: 0.8,
    roughness: 0.15,
  },
  // === IZQUIERDA ARRIBA: roundedBox pequeño flotante ===
  {
    name: "Mini Tile L",
    geometry: "roundedBox",
    material: "standard",
    animation: "float",
    position: [-1, 2, 1],
    rotation: [0.15, 0.2, -0.1],
    scale: [0.7, 0.7, 0.15],
    color: "#818cf8",
    metalness: 0.6,
    roughness: 0.2,
  },
];

// Negro puro para el look tipo Spline
export const epicHeroEnvironment = "night";
