import type { SceneObject } from "../store/scene";

export const glassHeroTemplate: Omit<SceneObject, "id">[] = [
  {
    name: "Glass Sphere",
    geometry: "sphere",
    material: "transmission",
    animation: "float",
    position: [0, 1, 0],
    rotation: [0, 0, 0],
    scale: [1.5, 1.5, 1.5],
    color: "#a78bfa",
    metalness: 0,
    roughness: 0,
    transmission: 0.95,
    thickness: 0.5,
  },
  {
    name: "Torus Ring",
    geometry: "torus",
    material: "standard",
    animation: "rotate",
    position: [0, 1, 0],
    rotation: [Math.PI / 4, 0, 0],
    scale: [2, 2, 2],
    color: "#f472b6",
    metalness: 0.8,
    roughness: 0.2,
  },
  {
    name: "Wobbly Cube",
    geometry: "box",
    material: "wobble",
    animation: "float",
    position: [-2.5, 0.5, -1],
    rotation: [0, 0.5, 0],
    scale: [0.8, 0.8, 0.8],
    color: "#38bdf8",
    metalness: 0.3,
    roughness: 0.4,
    distort: 0.3,
    speed: 1.5,
  },
  {
    name: "Dodecaedro",
    geometry: "dodecahedron",
    material: "distort",
    animation: "none",
    position: [2.5, 0.8, -0.5],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    color: "#34d399",
    metalness: 0.5,
    roughness: 0.3,
    distort: 0.2,
    speed: 3,
  },
];
